In [ ]:
import torch

B = 2
N = 50
S = 5

device = torch.device('cuda' if torch.cuda.is_available else 'cpu')
group_idx = torch.arange(N, dtype=torch.long).to(device).view(1, 1, N).repeat([B, S, 1])
print(group_idx)

In [ ]:
import time
start = time.time()
def square_distance_my(original_larger_pc, sampled_centroid_point):
    """
    Calculate the pairwise distance between point in the original point cloud and each sampled centroid point.

    src^T * dst = xn * xm + yn * ym + zn * zm;
    sum(src^2, dim=-1) = xn*xn + yn*yn + zn*zn;
    sum(dst^2, dim=-1) = xm*xm + ym*ym + zm*zm;
    dist = (xn - xm)^2 + (yn - ym)^2 + (zn - zm)^2
         = sum(src**2,dim=-1)+sum(dst**2,dim=-1)-2*src^T*dst

    Input:
        original_larger_point: [B, N, C]
        sampled_centroid_point: [B, M, C]   M represent the subset of sampled points from N original larger input point cloud
    Output:
        pairwise_eucl_dist: per-point square distance, [B, N, M]
    """
    B, N, C = original_larger_pc.shape
    B, M, C = sampled_centroid_point.shape
    euclidean_distance = torch.zeros((B,N,M))
    for k in range(B):
        for i in range(N):
            for j in range(M):
                euclidean_distance[k, i, j] = ((original_larger_pc[k, i, 0] - sampled_centroid_point[k,j,0])**2 + (original_larger_pc[k, i, 1] - sampled_centroid_point[k,j,1])**2)

    return euclidean_distance        

src = torch.tensor([[[-2,3], [3,1], [4,-2], [6,3], [5,1], [2,-3]],
                    [[-2,3], [3,1], [4,-2], [6,3], [5,1], [2,-3]]])
dst = torch.tensor([[[-2,3], [6,3], [2,-3]],
                    [[-2,3], [6,3], [2,-3]]])
print(square_distance_my(src.to(device), dst.to(device)))
end = time.time()
print(f"time:", (end - start)*1000)

x = torch.randint(0, 10, (2,), dtype=torch.long)
print(x)

In [ ]:
import numpy as np
path = './data/train_keyframes/scene-0871_frame26.npy'
np_array = np.load(path, 'r')
print(np.min(np_array[:, 3]), np.max(np_array[:, 3]), np.mean(np_array[:, 3]))
print(np.min(np_array[:, 4]), np.max(np_array[:, 4]), np.mean(np_array[:, 4]))
print(np.min(np_array[:, 5]), np.max(np_array[:, 5]), np.mean(np_array[:, 5]))

In [18]:
import torch
count = torch.cuda.device_count()
print(count)

1


In [ ]:
import numpy as np
import os
data_root = './data/train_keyframes/'
frame = 'scene-0122_frame26.npy'
frame_path = os.path.join(data_root, frame)
data = np.load(frame_path, 'r')
#print(data[:, 6])
print(data[:20, 3:6])


In [ ]:
import numpy as np
import os
data_root = './logs/PointNet++_original_hyperparameters/2023-08-13_00-55/checkpoint_epoch66_npy_predictions/'
#frame = 'scene-0014_frame29.npy'
frame_path = os.path.join(data_root, frame)
data = np.load(frame_path, 'r')
#print(data[:, :10, :])
print(data.shape)
data_reshape = data.reshape(data.shape[1], data.shape[2])
print(data_reshape.shape)
#print(np.argmax(data_reshape, axis=1))
index_counts = np.bincount(np.argmax(data_reshape, axis=1))
for index, count in enumerate(index_counts):
    print(f"Index {index} occurs {count} times")


torchscript_data_root = './logs/PointNet++_original_hyperparameters/2023-08-13_00-55/torchscript_epoch66_npy_predictions/'
torchscript_frame_path = os.path.join(torchscript_data_root, frame)
ts_data = np.load(torchscript_frame_path, 'r')
#print(data[:, :10, :])
print(ts_data.shape)
ts_data_reshape = data.reshape(ts_data.shape[1], ts_data.shape[2])
print(ts_data_reshape.shape)
#print(np.argmax(ts_data_reshape, axis=1))
ts_index_counts = np.bincount(np.argmax(ts_data_reshape, axis=1))
for ts_index, ts_count in enumerate(ts_index_counts):
    print(f"TS_Index {ts_index} occurs {ts_count} times")

In [44]:
import numpy as np
import os
import torch
data_root = './TrainingTooling_Data/nuScenes_dataset_in_AtCity_format/vjaiswalEnd2End/data/newreltime_val_keyframes/'
frame = 'scene-0003_frame2.npy'
frame_path = os.path.join(data_root, frame)
data = np.load(frame_path, 'r')
#print(data[:, 6])
print(data.shape)
#print(data[:2, :])
print(data.dtype)
frame_radar_point_data = torch.tensor(data[20:32, [0, 1, 2, 7,8, 15, 16]])
frame_radar_point_label = torch.tensor(data[20:32, -1])
print(frame_radar_point_data, frame_radar_point_label)
print(frame_radar_point_label.dtype)
#data = data.astype(int)
#print(np.argmax(data_reshape, axis=1))
#index_counts = np.bincount(data[:, -1])
#print(index_counts)
#for index, count in enumerate(index_counts):
    #print(f"Index {index} occurs {count} times")

(935, 18)
float64
tensor([[-3.7860e+00, -2.5187e+01, -7.8103e-01,  1.5000e+00,  1.0000e+00,
         -1.1245e-01, -3.2063e-02],
        [-5.0944e+00, -2.8425e+01, -7.8133e-01,  2.5000e+00,  1.0000e+00,
         -3.0244e-02, -9.1614e-03],
        [-4.4321e+00, -3.0607e+01, -7.8121e-01,  2.5000e+00,  1.0000e+00,
         -6.9875e-02, -1.8177e-02],
        [-3.6590e+00, -6.4799e+01, -7.8136e-01,  2.5000e+00,  1.0000e+00,
         -8.2007e-02, -1.0154e-02],
        [-1.2244e+01, -6.5443e+01, -7.8319e-01,  5.5000e+00,  1.0000e+00,
         -6.6255e-02, -1.7028e-02],
        [-4.7150e+01, -6.9238e+01, -7.9062e-01,  1.0000e+01,  1.0000e+00,
         -7.5137e-02, -5.7754e-02],
        [ 2.4138e+00, -4.0016e+00, -7.7952e-01,  3.0000e+00,  1.0000e+00,
         -7.0434e-02, -2.2011e-03],
        [ 1.9506e+00, -8.8167e+00, -7.7966e-01, -1.0000e+00,  1.0000e+00,
         -5.7578e-02, -5.0381e-03],
        [ 2.4141e+00, -4.0018e+00, -7.7924e-01,  3.5000e+00,  2.0000e+00,
         -6.8934e-02, -2.154

In [8]:
import numpy as np
import os
import torch
data_root = './TrainingTooling_Data/nuScenes_dataset_in_AtCity_format/vjaiswalEnd2End/data/Data_with_stationary_moving_NOSWEEPS/train_keyframes/'
frame = 'scene-0002_frame2.npy'
frame_path = os.path.join(data_root, frame)
data = np.load(frame_path, 'r')
#print(data[:, 6])
print(data.shape)
print(data[:200, 8])
print(data.dtype)

#inference_data = data[data[:, 8] == 0, :]
#print(inference_data.shape, inference_data[:, 8])
#print(data[:inference_data.shape[0]+2, 8])
#frame_radar_point_data = torch.tensor(data[100:200, [8]])
#frame_radar_point_label = torch.tensor(data[30:50, -1])
#print(frame_radar_point_data, frame_radar_point_label)
#print(frame_radar_point_label.dtype)
#data = data.astype(int)
#print(np.argmax(data_reshape, axis=1))
#index_counts = np.bincount(data[:, -1])
#print(index_counts)
#for index, count in enumerate(index_counts):
    #print(f"Index {index} occurs {count} times")

(1382, 18)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 2. 2. 2.]
float64


In [9]:
import numpy as np
import os
from natsort import natsorted
data_root = './TrainingTooling_Data/nuScenes_dataset_in_AtCity_format/vjaiswalEnd2End/data/Data_with_stationary_moving_NOSWEEPS/train_keyframes/'
all_frames = natsorted(os.listdir(data_root))
max = 0
j = 0
that_idx = 0
print(all_frames[:1], len(all_frames))
for i in range(len(all_frames)):
    frame_file_path = os.path.join(data_root, all_frames[i])
    data = np.load(frame_file_path)
    if data.shape[0] > max:
        max = data.shape[0]
        that_idx = i
    else:
        max = max
    j = i
print(max, that_idx)
print(all_frames[that_idx])



min = 300
k = 0
min_idx = 0
print(all_frames[:1])
for i in range(len(all_frames)):
    frame_file_path = os.path.join(data_root, all_frames[i])
    data = np.load(frame_file_path)
    if data.shape[0] < min:
        min = data.shape[0]
        min_idx = i
    else:
        min = min
    j = i
print(min, min_idx)
print(all_frames[min_idx])



['scene-0001_frame1.npy'] 28130
342 14294
scene-0517_frame33.npy
['scene-0001_frame1.npy']
36 4516
scene-0185_frame27.npy


In [31]:
a = np.array([[0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089]])

unique_values, counts = np.unique(a, return_counts=True)
#print(unique_values, counts)
# Calculate the cumulative sum of counts
cumulative_counts = np.cumsum(counts)
#print(cumulative_counts)
# Create a new array based on cumulative counts
result = np.zeros(cumulative_counts[-1], dtype=int)
# Assign values to the new array based on unique values and their counts
# Assign values to the new array based on cumulative counts
for i, count in enumerate(cumulative_counts):
    if i > 0:
        result[cumulative_counts[i - 1]:count] = i

#print(result)
new_unique_values, new_counts = np.unique(result, return_counts=True)
#print(new_unique_values, new_counts)
#print(cumulative_counts[-1])

x = np.zeros((18,34), dtype=int)
#print(x.shape)
#print(x[:, 0:20])
data_radar = np.empty((18,1))
print(data_radar)
data_radar = np.concatenate((data_radar, x), axis=1)
print(data_radar, data_radar.shape)

[[9.14889568e-312]
 [0.00000000e+000]
 [3.18299369e-313]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [1.06099790e-312]
 [1.39736850e-076]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [3.81959242e-313]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]]
[[9.14889568e-312 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000

In [37]:
a = np.array([[0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.01395106, 0.01395106,
        0.01395106, 0.01395106, 0.01395106, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.08425093, 0.08425093, 0.08425093, 0.08425093,
        0.08425093, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.15932608, 0.15932608,
        0.15932608, 0.15932608, 0.15932608, 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 , 0.2335999 ,
        0.2335999 , 0.2335999 , 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.30367589, 0.30367589, 0.30367589,
        0.30367589, 0.30367589, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089,
        0.37934089, 0.37934089, 0.37934089, 0.37934089, 0.37934089]])

unique_values, counts = np.unique(a, return_counts=True)
#print(unique_values, counts)
# Calculate the cumulative sum of counts
cumulative_counts = np.cumsum(counts)
#print(cumulative_counts)
# Create a new array based on cumulative counts
result = np.zeros((1,cumulative_counts[-1]), dtype=int)
# Assign values to the new array based on unique values and their counts
# Assign values to the new array based on cumulative counts
# Create an array of indices for each timestamp based on cumulative counts
timestamp_indices = np.arange(cumulative_counts[-1])

# Calculate which relative timestamp each point belongs to
relative_timestamps = np.searchsorted(cumulative_counts, timestamp_indices, side='right')

# Assign the relative timestamps to the corresponding locations in the array
result[:, timestamp_indices] = relative_timestamps
print(result)
"""
for i, count in enumerate(cumulative_counts):
    if i > 0:
        result[cumulative_counts[i - 1]:count] = i

#print(result)
new_unique_values, new_counts = np.unique(result, return_counts=True)
#print(new_unique_values, new_counts)
#print(cumulative_counts[-1])

x = np.zeros((18,34), dtype=int)
#print(x.shape)
#print(x[:, 0:20])
data_radar = np.empty((18,1))
print(data_radar)
data_radar = np.concatenate((data_radar, x), axis=1)
print(data_radar, data_radar.shape)

num_timestamps = cumulative_counts[-1]
relative_timestamp_feat = np.zeros((1, num_timestamps), dtype=int)
"""


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2
  2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
  2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
  3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
  4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]]


'\nfor i, count in enumerate(cumulative_counts):\n    if i > 0:\n        result[cumulative_counts[i - 1]:count] = i\n\n#print(result)\nnew_unique_values, new_counts = np.unique(result, return_counts=True)\n#print(new_unique_values, new_counts)\n#print(cumulative_counts[-1])\n\nx = np.zeros((18,34), dtype=int)\n#print(x.shape)\n#print(x[:, 0:20])\ndata_radar = np.empty((18,1))\nprint(data_radar)\ndata_radar = np.concatenate((data_radar, x), axis=1)\nprint(data_radar, data_radar.shape)\n\nnum_timestamps = cumulative_counts[-1]\nrelative_timestamp_feat = np.zeros((1, num_timestamps), dtype=int)\n'

In [6]:
import torch
def class_weight(data_root, train):
    if train == True:
        train_data_root = os.path.join(data_root, "train_keyframes")
    else:
        train_data_root = os.path.join(data_root, "val_keyframes")
    all_frames = natsorted(os.listdir(train_data_root))
    all_targets = []
    for i in range(len(all_frames)):
        current_frame_name = all_frames[i]
        current_frame_file_path = os.path.join(train_data_root, current_frame_name)
        target = np.load(current_frame_file_path, 'r')[:, -1]
        all_targets.append(target)
    results_targets = np.hstack(all_targets).astype(float)
    index_counts = torch.histc(torch.tensor(results_targets), bins=6, min=0, max=5)

    return index_counts


data_root = './TrainingTooling_Data/nuScenes_dataset_in_AtCity_format/vjaiswalEnd2End/data/'

class_counts = class_weight(data_root, train= False)
print(class_counts)
class_frequencies = class_counts / (torch.sum(class_counts))
print(class_frequencies)
inverse_class_frequencies = 1.0 / (class_frequencies + 1e-6)
print(inverse_class_frequencies)


tensor([  90616.,  259511.,  453208.,   32541.,   11503., 6486614.],
       dtype=torch.float64)
tensor([0.0124, 0.0354, 0.0618, 0.0044, 0.0016, 0.8845], dtype=torch.float64)
tensor([ 80.9283,  28.2600,  16.1821, 225.3262, 637.1660,   1.1306],
       dtype=torch.float64)


In [30]:
import numpy as np

# Create a sample array of shape N,18
data = np.random.rand(5, 18)

# Extract columns 0, 1, 2, 7, 15, and 16
selected_columns = data[:, [0, 1, 2, 7, 15, 16]]

print("Original data:")
print(data)
print("\nSelected columns:")
print(selected_columns)

Original data:
[[0.67850841 0.24394496 0.04997865 0.91241903 0.93730592 0.62516909
  0.34739785 0.35402426 0.39355866 0.04094832 0.52505856 0.41492457
  0.28283608 0.08239358 0.94678283 0.5168608  0.28823134 0.76313039]
 [0.86711193 0.86019648 0.54025246 0.75559447 0.21071811 0.77898976
  0.18341398 0.5413501  0.83238507 0.10919038 0.72458331 0.40293265
  0.89346082 0.20008661 0.57476995 0.05664437 0.91791576 0.73537813]
 [0.25855508 0.22619698 0.6150341  0.48653924 0.21408806 0.83655874
  0.21794372 0.75657985 0.30213868 0.46717864 0.77525019 0.87286572
  0.53098937 0.03247781 0.5784415  0.03871108 0.1805793  0.28979083]
 [0.05189511 0.25578662 0.13916935 0.32660335 0.13995938 0.33764254
  0.58428401 0.82524138 0.31066672 0.43496553 0.25857686 0.41138442
  0.73953919 0.30650498 0.01759187 0.42241034 0.79766364 0.1091572 ]
 [0.50227621 0.26802609 0.14472621 0.9027622  0.80756931 0.59895201
  0.0330912  0.69591854 0.70271183 0.16452625 0.87448878 0.07957277
  0.51145584 0.31681    0.762

In [ ]:
"""Precision recall curve Script which Later I changed because the confusion matrix was calculated on 45 thresholds which was not need for semantic segmentation case"""

import os
import sys
import numpy as np
import math
from pathlib import Path
import h5py
import json
from natsort import natsorted
import matplotlib.pyplot as plt

# Add the root folder to the Python path
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = BASE_DIR
sys.path.insert(0, ROOT_DIR)

def Precision_Recall(cm):
    """
    This function returns class-wise TPR, FNR, FPR & TNR
    [[cm]]: a 2-D array of a multiclass confusion matrix
            where horizontal axes represent actual classes
            and vertical axes represent predicted classes
    {output}: a dictionary of class-wise accuracy parameters
    """
    dict_metric = dict()
    num_classes = len(cm[0])
    row_sums = cm.sum(axis=1)          # gives total positives samples
    col_sums = cm.sum(axis=0)          # gives total predicted samples
    array_sum = sum(sum(cm))
    #initialize a blank nested dictionary
    for i in range(1, num_classes+1):
        keys = str(i)
        dict_metric[keys] = {"Precision":0, "Recall":0}
    # calculate and store class-wise Precision and Recall
    for i in range(num_classes):
        for j in range(num_classes):
            if i == j:
                keys = str(i+1)
                tp = cm[i, j]
                
                dict_metric[keys]["Precision"] = tp / col_sums[i]
                dict_metric[keys]["Recall"] = tp / row_sums[i]



def main():

    machine_config_json_path = os.path.join("configs", "machine_configs", "machine_config_local.json")
    with open(machine_config_json_path, "r") as local_config:
        local_config_data = json.load(local_config)

    logs_dir = local_config_data.get("model_path")
    logs_dir = os.path.join(ROOT_DIR, logs_dir)
    logs_dir = Path(logs_dir)
    conf_matrix_dir = logs_dir.joinpath('PointNet++_original_hyperparameters')
    conf_matrix_dir = conf_matrix_dir.joinpath('baseline_with_focalloss_weight_on_whole_data')
    conf_matrix_dir = conf_matrix_dir.joinpath('checkpoint_epoch95_h5_confusion_matrix')
    conf_matrices = natsorted(os.listdir(conf_matrix_dir))
    score_thresholds = [0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.24, 0.26, 0.28, 0.3, 0.32, 0.34, 0.36, 0.38, 0.4, 0.42, 0.44, 0.46, 0.48, 0.5, 0.52,
                    0.54, 0.56, 0.58, 0.6, 0.62, 0.64, 0.66, 0.68, 0.7, 0.72, 0.74, 0.76, 0.78, 0.8, 0.82, 0.84, 0.86, 0.88, 0.9, 0.92, 0.94, 0.96, 0.98]
    
    sum_conf_matrices = np.zeros((45,6,6), dtype=np.int32)
    for matrix in conf_matrices:
        each_matrix_path = os.path.join(conf_matrix_dir, matrix)
        with h5py.File(each_matrix_path, 'r') as matrix_file:
            nocare_false = matrix_file['nocare_false']   
            matrix_data = nocare_false['confus']  # order is true, pred, num_thresholds
            #creating an empty confusion matrix of shape 6*6 initialized with zeros
            matrix_data = np.array(matrix_data).transpose(2, 0, 1)           # order changed to num_thresholds, true, pred
            sum_conf_matrices += matrix_data

    class_colors = ['red', 'blue', 'orange', 'green', 'yellow', 'black']
    line_styles = ['-', '--', '-.', ':', 'solid', 'dashed']
    Classes = {'0': 'Background','1': 'Vehile Large','2': 'Vehicle','3': 'Pedestrian','4': 'Bike','5': 'Other'}

    plt.figure()
    for class_idx in range(6):
        precision_list = []
        recall_list = []
        for i in range(len(score_thresholds)):
            dict_metric = Precision_Recall(sum_conf_matrices[i, :, :])   
            precision = dict_metric[str(class_idx + 1)]['Precision']
            if math.isnan(precision):
                continue
            else:
                precision_list.append(precision)
                recall= dict_metric[str(class_idx + 1)]['Recall']
                recall_list.append(recall)

        plt.plot(precision_list, recall_list, label=f'Class {Classes[str(class_idx)]}', color=class_colors[class_idx], linestyle=line_styles[class_idx])

    plt.title('Precision Recall curve')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.legend(loc='best')
    plt.show()

main()

"""
sample = np.array([[15, 2, 1],
                   [3, 15, 1],
                   [1, 4, 15]])
dict_metric = Precision_Recall(sample)
"""

In [ ]:
" Data Loader when it was padded with 0 for data and -1 for labels"

from torch.utils.data import DataLoader
from build_dataset.dataset import Nuscenes_RadarPC_Dataset
import os
import torch
from torch.nn.utils.rnn import pad_sequence

def custom_collate_fn(batch):
    # Pad sequences to make them of the same length
    data_batch = [item[0] for item in batch]
    labels_batch = [item[1] for item in batch]
    frame_name = [item[2] for item in batch]
    padding_label_value = -1

    #max_sequence_length for padding
    max_length = max(data.shape[0] for data in data_batch)

    # Pad data sequences
    data_padded = pad_sequence(data_batch, batch_first=True, padding_value=0)
    # Pad labels with -1 to distinguish from actual labels (0 to 5)
    labels_padded = [torch.cat([labels, torch.full((max_length - labels.shape[0],), padding_label_value, dtype=torch.long)]) for labels in labels_batch]
    labels_padded = torch.stack(labels_padded)
    # Create a mask to ignore padded labels during loss computation
    mask = (labels_padded != padding_label_value)
    return data_padded, labels_padded, mask, frame_name


#  to wrap an iterable around Dataset enabling easy access to the samples
def data_loader(data_root, batch_size, train, num_workers, pin_memory):
    
    if train == True:
        train_data_path = os.path.join(data_root, "train_keyframes", "")
        train_dataset = Nuscenes_RadarPC_Dataset(data_root=train_data_path)
        dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=pin_memory, collate_fn=custom_collate_fn, drop_last=True)

    else:
        val_data_path = os.path.join(data_root, "val_keyframes", "")
        val_dataset = Nuscenes_RadarPC_Dataset(data_root=val_data_path)
        dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=pin_memory)

    return dataloader

if __name__ == "__main__":
    
    batch_size = 4
    root = './TrainingTooling_Data/nuScenes_dataset_in_AtCity_format/vjaiswalEnd2End/data/'
    dataloader = data_loader(data_root=root, batch_size=batch_size, train=True, num_workers=2, pin_memory=0)
    tb = 0
    for i, (data, labels, mask, frame_name, class_frequency) in enumerate(dataloader):
        print(data.shape, labels.shape, mask.shape)
        tb += 1
    print(tb)   

In [33]:
import os
import numpy as np


data_root = './TrainingTooling_Data/nuScenes_dataset_in_AtCity_format/vjaiswalEnd2End/data/'
folder_path = os.path.join(data_root, "train_keyframes")  # Replace with the actual folder path
correct_npy_files = []

# Iterate through the files in the folder
for idx, file_name in enumerate(os.listdir(folder_path)):
    if file_name.endswith(".npy"):
        file_path = os.path.join(folder_path, file_name)
        try:
            # Attempt to load the file to check for pickled data
            data = np.load(file_path, allow_pickle=False)
            correct_npy_files.append((file_name))
        except ValueError as e:
            if "Cannot load file containing pickled data" in str(e):
                print(f"Skipping file {file_name} due to pickled data issue")
                continue  # Skip to the next iteration
                #npy_files_with_pickled_issue.append((idx, file_name))

print("Number of .npy files with pickled data issue:", len(npy_files_with_pickled_issue))

# Print index and file name for each problematic file
for idx, file_name in npy_files_with_pickled_issue:
    print(f"Index: {idx}, File: {file_name}")

Number of .npy files with pickled data issue: 0


In [1]:
import numpy as np
import os
import torch
data_root = './logs/PointNet++_original_hyperparameters/6_PaperArchitecture_Pad0-1_16_NumWo6_50_1e-3_20_0.5/checkpoint_epoch25_npy_predictions/'
frame = 'scene-0003_frame1.npy'
frame_path = os.path.join(data_root, frame)
data = np.load(frame_path, 'r')
print(data)
#print(data[:, 6])
#print(data.shape)
#print(data[:2, :])
#print(data.dtype)
#frame_radar_point_data = torch.tensor(data[:2, [0, 1, 2, 7, 15, 16]])
#frame_radar_point_label = torch.tensor(data[:2, -1])
#print(frame_radar_point_data, frame_radar_point_label)
#print(frame_radar_point_label.dtype)
#data = data.astype(int)
#print(np.argmax(data_reshape, axis=1))
#index_counts = np.bincount(data[:, -1])
#print(index_counts)
#for index, count in enumerate(index_counts):
    #print(f"Index {index} occurs {count} times")

[[[0.13746317 0.14271352 0.13599609 0.07946634 0.13314667 0.37121427]
  [0.2435165  0.09190841 0.16223449 0.12078015 0.21179003 0.16977055]
  [0.22234337 0.1058269  0.15778023 0.11311816 0.18265638 0.21827495]
  [0.18879935 0.13617933 0.13309108 0.06782927 0.12021647 0.35388452]
  [0.20239516 0.14665665 0.1284584  0.05656371 0.09103625 0.37488988]
  [0.18011338 0.14223598 0.12402354 0.05978188 0.10116    0.39268517]
  [0.14907166 0.14342202 0.12553288 0.07436088 0.11247776 0.39513475]
  [0.17608753 0.15841405 0.133594   0.06870616 0.14945178 0.31374648]
  [0.1417522  0.14272805 0.14013737 0.07374226 0.14360261 0.35803756]
  [0.13132027 0.2606394  0.09261864 0.04673263 0.06791212 0.40077698]
  [0.13034964 0.14532945 0.13473438 0.08330745 0.13030913 0.37597   ]
  [0.13919015 0.14361583 0.14055565 0.07575537 0.1442205  0.3566625 ]
  [0.18046436 0.13934052 0.14985721 0.04464339 0.11779872 0.3678958 ]
  [0.13746317 0.14271352 0.13599609 0.07946634 0.13314667 0.37121427]
  [0.24436854 0.0910